### ISSUE TITLE
Instructions for globbing/bracket-absolute doesn't explain what is needed to complete the challenge

### ISSUE THREAD

**Issue by anOwlNamedMavis** [pwncollege/linux-luminarium#16]
The instructions for `globbing/bracket-absolute` don't explain the challenge or anything about absolute paths - it seems to just be copy-pasted from `globbing/bracket` with some minor wording changes.

I was able to solve the challenge from error outputted by `/challenge/run` but ideally the conditions would be documented in the instructions

**Comment by zardus** [comment]
Thanks for reporting this! Fixed :-)
